apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  selector:
    matchLabels:
      run: busybox
  template:
    metadata:
      labels:
        run: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        securityContext:
            privileged: true
        volumeMounts:
          - name: host
            mountPath: /host
        args: ["sleep", "infinity"]
      hostNetwork: true
      volumes:
      - name: host
        hostPath:
          path: /
          type: Directory
